server:
  port: 8082
spring:
  profiles:
    active: native
  application:
    name: AUTH
  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/academic_system?useUnicode=true&characterEncoding=utf8
    username: root
    password: ENC(AtWACilYZxmh2RXbeeEIHQxh6w4YfIZV)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect:
        '[format_sql]': true
        '[use_sql_comments]': true
        '[order_insert]': true
        '[order_updates]': true
        '[generate_statistics]': true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8085/eureka/
  instance:
    hostname: localhost
jasypt:
  encryptor:
    password: secret
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
logging:
  file:
    name: logs/auth.log
    max-size: 10MB
    max-history: 365
  level:
    root: INFO
    '[org.hibernate.sql]': DEBUG
    '[org.hibernate.type.descriptor.sql]': TRACE
management:
  endpoints:
    web:
      base-path: /act
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
    ping:
      enabled: true
    livenessstate:
      enabled: true
